### PR TITLE
FIX: api key header error

### PR DESCRIPTION
**Pull request by devhaozi**
According to the documentation of huggingface: `By default the server responds to every request. With an api key set, the requests must have the Authorization header set with the api key as Bearer token.`, the use of API_KEY in the plugin is incorrect, and should use Bearer Token.

Source doc url: [https://github.com/huggingface/text-embeddings-inference?tab=readme-ov-file#docker](https://github.com/huggingface/text-embeddings-inference?tab=readme-ov-file#docker)

### CODE REVIEW

**Comment by xfalcox** [comment]
Our implementation predates TEI support for API keys by a couple months, so we relied on a reverse proxy doing API Key header verification that uses this signature, meaning we can't simply merge this.

**Comment by devhaozi** [comment]
> Our implementation predates TEI support for API keys by a couple months, so we relied on a reverse proxy doing API Key header verification that uses this signature, meaning we can't simply merge this.

If so, what do you think about adding both the `X-API-KEY` and `Authorization` headers?

**Comment by devhaozi** [comment]
@xfalcox fixed, PTAL.

**Comment by SamSaffron** [comment]
@xfalcox what should we do here?

**Comment by xfalcox** [comment]
Hey @devhaozi I have rebased it at https://github.com/discourse/discourse-ai/pull/839 and tests pass. Can you rebase it properly, or can I merge #839 ?

**Comment by devhaozi** [comment]
> Hey @devhaozi I have rebased it at #839 and tests pass. Can you rebase it properly, or can I merge #839 ?

Yes, you can.

**Pull request closed without merging**
